pathInfo:
  inputDir: "/home/esp/Machine_Learning/11_pdb_dataset/01_dataset_pdbs"
  outDir: "/home/esp/Machine_Learning/11_pdb_dataset/02_features"
  msmsDir: "/home/esp/bin/MSMS"
  aminoAcidTable: "/home/esp/Machine_Learning/11_pdb_dataset/00_scripts/multiCaveFeatures/amino_acid_properties.txt"
optionsInfo:
  genCofactorLabels: True
  genAminoAcidCategories: True
  keepIndividualCounts: False
  normaliseCounts: False
  keepTotalCounts: True